### ISSUE TITLE
CANNOT REREGISTER 

### ISSUE THREAD

**Issue by Jiajing-Hu** [soramimi/qSIP#2]
I get a sip account on linphone server
i can login in other sip phone such as boghe and linphone 
but I cant login in qsip

**Comment by Jiajing-Hu** [comment]
the problem is solved.
It's my fault,your program is good.thank you sir!

**Comment by soramimi** [comment]
:smiley:

**Comment by Jiajing-Hu** [comment]
Sorry ~sir
I got another problem makes me annoyed.
I can register on my sip server ( qSIP UA_EVENT_REGISTER_OK) , but whatever I call ,I got a 404 not found.
But when I use other softphone, I can call others with the same account

I think maybe I make something wrong. Could you pls give me some advices?
Thanks!


——————————————————————————
E-mail ： hujiajing.xdu@outlook.com

________________________________
发件人: soramimi <notifications@github.com>
发送时间: Tuesday, December 18, 2018 11:17:49 PM
收件人: soramimi/qSIP
抄送: Jiajing-Hu; Author
主题: Re: [soramimi/qSIP] CANNOT REREGISTER (#2)


😃

**Comment by soramimi** [comment]
I am trying Linphone now, but I can not do that account setup well. The mechanism may be slightly different from the SIP server I know.
